### ISSUE TITLE
Display nested symlink for projected content

### ISSUE THREAD

**Issue by AleksanderBodurri** [rangle/angular-devtools#252]
<img width="475" alt="Screen Shot 2020-04-06 at 1 28 35 PM" src="https://user-images.githubusercontent.com/39253660/78587191-98654080-780a-11ea-820d-d4c28535c04d.png">
<img width="680" alt="Screen Shot 2020-04-06 at 1 28 56 PM" src="https://user-images.githubusercontent.com/39253660/78587213-9d29f480-780a-11ea-8b85-18b9b03f206f.png">

**Comment by mgechev** [comment]
Let's close for now and see if the community needs this.
