### ISSUE TITLE
Virtual scrolling bug

### ISSUE THREAD

**Issue by mgechev** [rangle/angular-devtools#342]
Not sure what are the exact steps to reproduce, but once in a while (once every 20-30 times I open devtools) the directive explorer shows only a part of the list, the rest of it is just blank.

Keeping this as a placeholder for when we find steps to reproduce it.

**Comment by naticaceres** [comment]
I installed Angular devtools a few days ago in my personal computer and it's been working great.

Installed it today in my work computer - the first time I opened it with my work project (angular V11.0.9) I got [this issue ](https://s3.gifyu.com/images/2021-05-21_13-34-31.gif) (in the gif I am scrolling using the mouse wheel).

I arrived to this closed issue here and looked into other issues with the 'scroll' keyword.
I picked up it was something with resizing.
I resized the devtools width and it fixed itself.
Didn't see it occur eversince, but I decided to post my experience here in case it can be of any help to narrow down the issue.

btw great job! I'm loving devtools, it is making my work so much easier <3
