### ISSUE TITLE
Truncate arrays larger than length 100

### ISSUE THREAD

**Issue by AleksanderBodurri** [rangle/angular-devtools#563]
Example of how chrome devtools does it:

n = 1000
<img width="641" alt="Screen Shot 2020-12-14 at 1 49 52 PM" src="https://user-images.githubusercontent.com/39253660/102122366-5f5a8280-3e13-11eb-8887-7afff44f89af.png">

n = 101
<img width="491" alt="Screen Shot 2020-12-14 at 1 52 21 PM" src="https://user-images.githubusercontent.com/39253660/102122540-9a5cb600-3e13-11eb-9a33-d8138f0447cc.png">

n = 100
<img width="479" alt="Screen Shot 2020-12-14 at 1 52 53 PM" src="https://user-images.githubusercontent.com/39253660/102122587-aba5c280-3e13-11eb-80dd-c8a601f20e4c.png">

Noticed that on large arrays, expanding the array is slow with angular devtools. This should improve performance.

**Comment by mgechev** [comment]
Closing for now because nobody has asked about this optimization yet.
