### ISSUE TITLE
Dev Tools Thinks My Application Running in Production mode

### ISSUE THREAD

**Issue by gokberknur** [rangle/angular-devtools#779]
_Description:_
When I try to run angular dev tools, it says:
 We detected an application built with production configuration. Angular DevTools only supports development builds. Also, there is an error in console window.

Also first line of console.log shows false for production value.

However, I think my application running in development mode.
...

**Angular Devtools version 1.0.0**:

**Angular version 10.2.4

**Date:** 19/05/2021

**OS:** Mac Os Catalina 10.15.7

Build configuration in angular .json

 "dev": {
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.prod.ts",
                  "with": "src/environments/environment.ts"
                }
              ]
            }

_Description of issue:_

![Screenshot 2021-05-19 at 09 23 27](https://user-images.githubusercontent.com/5589187/118772435-07bdb880-b884-11eb-8566-b27604ec3eaf.png)

my terminal during the build
![Screenshot 2021-05-19 at 09 26 38](https://user-images.githubusercontent.com/5589187/118810872-a6f6a600-b8ac-11eb-864d-ffd26d499707.png)

log of environment.ts object
![Screenshot 2021-05-19 at 14 24 54](https://user-images.githubusercontent.com/5589187/118812087-0b663500-b8ae-11eb-8be0-14612ecfb80d.png)

_Steps to reproduce:_

1. I run my dev server with npm start that is "    "start": "ng serve --proxy-config proxy.config.json -c dev",

2. on the landing page (also other pages), i see this error

**Comment by mgechev** [comment]
Thanks for the report! We can work on the messaging here, but basically you're seeing this message because of this line:

```
"optimization": true
```

**Comment by gokberknur** [comment]
Thank you! that solved the issue. 

another thing i have noticed if i run command just 
"ng serve ng serve --proxy-config proxy.config.json"

that also wokrs! which is strange i was thinking npm start is doing exactly the same thing because in my package.json file it is like this:

" "scripts": {
    "ng": "ng",
    "start": "ng serve --proxy-config proxy.config.json --aot",

but anyways I can happiliy use this tool now, thanks a lot!
