### ISSUE TITLE
[Feature] RxJs spy for devtools

### ISSUE THREAD

**Issue by vugar005** [rangle/angular-devtools#781]
_Description:_
**🚀 Feature Request**

**Angular Devtools version (required)**: sooner the better :)

**Angular version (required):** any

**Date:** any

**OS:** any

_Demo test application:_
https://github.com/cartant/rxjs-spy-devtools
https://github.com/ardoq/rxjs-devtools

_Description of feature:_

Would be better to have a new tab which will spy RxJs. Please see https://github.com/cartant/rxjs-spy-devtools
For example: it will spy specific operator(such as tag) and show values on panel. Similar to NgRx devTools but for RxJs.

**Comment by mgechev** [comment]
Thanks for the report! We'll keep this one outside the scope of Angular DevTools and instead recommend the rxjs-devtools extension.
