### ISSUE TITLE
Permission not allowed to push PR

### ISSUE THREAD

**Issue by vugar005** [rangle/angular-devtools#784]
_Description:_
First of all, thanks for awesome tools. Right now trying to push my PR but there permission error
Error:  `You can't push to git://github.com/rangle/angular-devtools.git`
...

**Angular Devtools version (required)**: any

**Angular version (required):** any

**Date:** 05/19/2021

**OS:** any

_Description of issue:_

- Include (clipped) screenshot images if possible.

_Steps to reproduce:_

1. `git checkout -b get-color-theme-from-local` 

2. `git commit -m "initial commit"`

3. `git push origin get-color-theme-from-local`

_Additional details:_
Following https://github.com/rangle/angular-devtools/blob/main/CONTRIBUTING.md
Cloned the project via :`git clone git://github.com/rangle/angular-devtools`  according to [documentation](https://github.com/rangle/angular-devtools)
Also tried with `git clone https://github.com/rangle/angular-devtools.git`
....

**Comment by vugar005** [comment]
@mgechev  Thanks but how gonna we make PR to this github main branch?

**Comment by vugar005** [comment]
This issue can be resolved now, when you push PR to your forked project, you can see your pull request on https://github.com/rangle/angular-devtools/

**Comment by mgechev** [comment]
We updated the docs.
