### ISSUE TITLE
input values are not changing on the component tab

### ISSUE THREAD

**Issue by turnerran** [rangle/angular-devtools#786]
Hello,
I was very excited to use the Angulatr devtools this morning and i'm still exploring it. i have noticed that the extension doesn't update an input variable passed to a component while it's changing after the first time.
For example, i'm using the mat-checkbox component. once i change the value of the checkbox i see it changes to true (the model property) but when i change it again to be unchecked, the value doesn't change under the component tab as well. he same thing happens in other inputs. for example, a text input. the first key press is appearing but when i press another key it doesn't appear on the property unlessi'm going to another component and going back to the previous component. i think that fixing the live update could be a hugh benefit for this extension.
thanks a lot
![image](https://user-images.githubusercontent.com/55016001/118799557-88da7700-b8a7-11eb-90d0-ca04536fb4e3.png)

**Comment by mgechev** [comment]
Thanks for the report! We'll look into this.

**Comment by turnerran** [comment]
Thanks for the quick response!

**Comment by FireStormHR** [comment]
If this gets resolved, I think this feature request will become obsolete : https://github.com/rangle/angular-devtools/issues/805

**Comment by mgechev** [comment]
This fix would be part of 1.0.2.

**Comment by turnerran** [comment]
Thanks my friend!
When should the new version going to be published?

**Comment by mgechev** [comment]
It's out. Make sure you update :)

**Comment by turnerran** [comment]
I checked. It's working and it's a great extension my friend (:

בתאריך יום ד׳, 2 ביוני 2021, 21:46, מאת Minko Gechev ‏<
***@***.***>:
