### ISSUE TITLE
Add support for UI Router

### ISSUE THREAD

**Issue by penfold** [rangle/angular-devtools#790]
_Description:_
The components view in DevTools doesn't show any UI-View entries in the component tree. 

I assume this is due to no current support for UI Router.

**Angular Devtools version (required)**:
1.0.0

**Angular version (required):**
11.2.13

**Date:**
19 May 2021

**OS:**
Win 10 Chrome

**Comment by penfold** [comment]
Or could this be the same cause as https://github.com/rangle/angular-devtools/issues/773 ?

**Comment by mgechev** [comment]
@penfold yes, same issue. Would you give your project a try with v12? Should be easy to update.

**Comment by penfold** [comment]
@mgechev I've checked in out ng 12 assessment branch and its working correctly.

Now, I need to work through the other issues with ng 12. 

Many thanks,
Paul
