### ISSUE TITLE
Components not recognized within mat-dialog content

### ISSUE THREAD

**Issue by gs-scooter** [rangle/angular-devtools#791]
_Description:_
Even though components within a modal mat-dialog can be selected with the inspector, they don't show up in the tree.

**Angular Devtools version (required)**:
1.0

**Angular version (required):**
11.2.14

**Date:**
5/19/21

**OS:**
Win 10 Chrome

_Demo test application:_
https://stackblitz.com/edit/angular-dialog-devtools?file=src/app/app.component.ts

**Comment by mgechev** [comment]
Looks related to https://github.com/rangle/angular-devtools/issues/773.

Would you verify if you can still reproduce the issue with v12?

**Comment by gs-scooter** [comment]
I am able to reproduce the issue in v12.

**Comment by mgechev** [comment]
Thanks for the reproduction. We'll have a look.

**Comment by mgechev** [comment]
Found the cause of the issue. The material dialog inserts its content via a DOM API outside the application root.

The fix is relatively straightforward, but may have performance implications. We'll do some experimentation and see what's the right path to move forward.
