### ISSUE TITLE
BUG: Error thrown: Cannot read property 'directiveStart' of null

### ISSUE THREAD

**Issue by markwhitfeld** [rangle/angular-devtools#801]
**Angular DevTools version (required)**:
11.2.7

**Angular version (required):**
11.2.7

**Link to a minimal stackblitz reproduction (strongly encouraged):**
Not possible, happening in debugging production app

_Description of issue:_
The `LTreeStrategy` is assuming that there is data related to an item in the `LView` and it is giving an error when trying to retrieve the `directiveStart` property (of `null` in this case). 

- Include (clipped) screenshot images if possible.
![image](https://user-images.githubusercontent.com/1948265/118974468-25b61680-b973-11eb-8d1f-52e919b29d3e.png)

_Steps to reproduce:_

1. Serve my production app

2. Open browser window with angular tools open

3. Error!

_Additional details:_
In the `_extract` function 1 step up in the call stack, here is the state if the `LView` and the `TViewData`.
In this case you can see the index `i` === `22`.
![image](https://user-images.githubusercontent.com/1948265/118975601-7712d580-b974-11eb-8283-739289a57c58.png)

**Comment by markwhitfeld** [comment]
Submitted PR to fix the issue. 👍

**Comment by markwhitfeld** [comment]
@mgechev I'm not sure if this situation is possibly related to your comment here: https://github.com/rangle/angular-devtools/blob/88eced450c50a0b778a55a426850205794f56116/projects/ng-devtools-backend/src/lib/directive-forest/ltree.ts#L114

**Comment by markwhitfeld** [comment]
@mgechev What would cause this scenario where there is no corresponding data for a node?
Is this an entirely valid case, or is it a state that these nodes should not get into?
If this is an invalid state, is there some root cause in my app (or Angular) that created this state?
My PR just works around the exception by avoiding the call to get a prop of `null` and thereby skipping the invalid node.

**Comment by mgechev** [comment]
Thanks for the fix!

**Comment by markwhitfeld** [comment]
@mgechev It's a pleasure.
PS. Could you take a look at the questions in my previous comment? Are any of my concerns valid?
