### ISSUE TITLE
BUG: Needlessly accessing properties of an injected service

### ISSUE THREAD

**Issue by markwhitfeld** [rangle/angular-devtools#802]
**Angular DevTools version (required)**:
11.2.7

**Angular version (required):**
11.2.7

**Link to a minimal stackblitz reproduction (strongly encouraged):**
Not possible, production project.

_Description of issue:_

- Include (clipped) screenshot images if possible.
![image](https://user-images.githubusercontent.com/1948265/118976990-f654d900-b975-11eb-897e-1dc7485b9e14.png)

_Steps to reproduce:_

1. Serve project

2. open browser with angular dev tools opened

3. Error thrown internally (but caught, so it recovers but misses some information from the app tree)

_Additional details:_
It accesses the property `0` of a service provided at the component level.
It breaks with this particular service because it is based on a ES6 Proxy type that does not allow access to props that have not been explicitly defined.
The code with the error is in `_extract` of `LTreeStrategy`.
I will submit a PR shortly to just do an `Array.isArray` check on the item first.
![image](https://user-images.githubusercontent.com/1948265/118977661-b5a98f80-b976-11eb-83ca-ef49ed4b2a37.png)

**Comment by mgechev** [comment]
Thanks for the issue and the fix! It'll be part of the next release.
