### ISSUE TITLE
Simple refresh button for change detection.

### ISSUE THREAD

**Issue by daithyy** [rangle/angular-devtools#805]
**Angular version:**
10.0.14

**What feature do you want to see?**
Add a simple refresh button to help with change detection, currently you need to click on another component and back again to detect changes for new values.

**Why is it important to you?**
I will only have to click in one place this way and see what property value has been updated (in a form group for example).

**Describe functionality in details. Apply mocks if applicable:**
The user can click on a refresh button located next to the `Open component source` button that redisplays the list of inputs, outputs and properties with any new changes if detected.

![image](https://user-images.githubusercontent.com/25370364/119007858-87817b00-b989-11eb-9eb6-0b451f1e854c.png)

**Comment by FireStormHR** [comment]
Being able to have it happening live (opt in through settings) would of course be even more awesome, but what @daithyy desribes would also be great indeed

**Comment by mgechev** [comment]
This would be part of 1.0.2.
