### ISSUE TITLE
Improve pagination to move between change detection cycles

### ISSUE THREAD

**Issue by nikhilgrag** [rangle/angular-devtools#818]
**What feature do you want to see?**
Improve pagination to move between change detection cycles.

**Why is it important to you?**
My app is running 900+ change detection cycles on the home page.
To check the first cycle I will have to  click on "<" button 900 times.

**Describe functionality in details. Apply mocks if applicable:**
We can make it an input box, where I can directly enter the number of change detection cycle I want to check.

_Additional details:_
![image](https://user-images.githubusercontent.com/6318975/119603070-21be4480-be0a-11eb-96fa-decf5f1d7d85.png)

**Comment by mgechev** [comment]
@nikhilgrag you should be able to use horizontal scroll. Try shift+scroll to give it a try. Let me know how this works for you!

**Comment by nikhilgrag** [comment]
@mgechev Yes, the scroll is working. Thanks for the response :)
