### ISSUE TITLE
We detected an application built with production configuration. Angular DevTools only supports development builds.

### ISSUE THREAD

**Issue by mbasij1** [rangle/angular-devtools#820]
unfortunately, I have a bug that my *ngFor does not work in a special module of the project!
I tried to debug the angular and install angular Devtools and run it with ng s but angular Devtools says  
"We detected an application built with production configuration. Angular DevTools only supports development builds."
what should I do?

**Comment by conradkirschner** [comment]
It feels also a bit strange, that it's only possible to debug a angular application when it is in non production configuration.

**Comment by mbasij1** [comment]
thank you.
I forget to change the environment
```
export const environment = {
  production: false
};
```
