### ISSUE TITLE
Angular DevTools only supports development builds.

### ISSUE THREAD

**Issue by hugoebarboza** [rangle/angular-devtools#838]
**Angular DevTools version (required)**:

**Angular version (required):**

**Link to a minimal stackblitz reproduction (strongly encouraged):**

_Description of issue:_

- Include (clipped) screenshot images if possible.

_Steps to reproduce:_

1. ng serve

2. ng serve --configuration dev

3. I get the message "Angular DevTools only supports development builds."

_Additional details:_ packege.json
"scripts": {
    "ng": "ng",
    "start": "node --max-old-space-size=12192 ./node_modules/@angular/cli/bin/ng serve",
    "start:dev": "node --max-old-space-size=12192 ./node_modules/@angular/cli/bin/ng serve --configuration dev",
    "dev": "lite-server --baseDir=dist/odisdkp/",
    "watch": "node --max-old-space-size=12192 ./node_modules/@angular/cli/bin/ng build --watch",
    "build": "ng build",
    "test": "ng test",
    "lint": "node --max_old_space_size=12192 ./node_modules/eslint/bin/eslint --color --fix -c .eslintrc.js --ext .ts ./src/app",
    "compodoc": "npx compodoc -p src/tsconfig.compodoc.json src",
    "e2e": "ng e2e",
    "build:ssr": "ng build --prod && ng run odisdkp:server:production",
    "serve:ssr": "node dist/odisdkp-server/main.js",
    "build:client-and-server-bundles": "node --max-old-space-size=12192 ./node_modules/@angular/cli/bin/ng build --prod && ng run odisdkp:server",
    "prod": "node --max-old-space-size=12192 ./node_modules/@angular/cli/bin/ng build --configuration production",
    "fix-memory-limit": "cross-env LIMIT=12192 increase-memory-limit",
    "source": "node --max-old-space-size=12192 ./node_modules/@angular/cli/bin/ng build --prod --source-map",
    "stats": "node --max-old-space-size=12192 ./node_modules/@angular/cli/bin/ng build --prod --stats-json",
    "analyze": "webpack-bundle-analyzer dist/odisdkp/stats.json",
    "sanalyze": "source-map-explorer dist/odisdkp/main*js",
    "dev:ssr": "node --max-old-space-size=12192 ./node_modules/@angular/cli/bin/ng run odisdkp:serve-ssr",
    "prerender": "node --max-old-space-size=12192 ./node_modules/@angular/cli/bin/ng run odisdkp:prerender",
    "preinstall": "npm install -g http-server",
    "postinstall": "ngcc"
  },

_Additional details:_ angular.json / dev configuration

"dev": {
              "optimization": {
                "scripts": true,
                "styles": {
                  "minify": true,
                  "inlineCritical": true
                },
                "fonts": {
                  "inline": true
                }
              },
              "outputHashing": "all",
              "sourceMap": false,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.prod.ts",
                  "with": "src/environments/environment.ts"
                }
              ]
            }

**Comment by mgechev** [comment]
Seems like your app is using View Engine, rather than Ivy and DevTools is showing an inaccurate error message.

Make sure you're using the latest Angular DevTools 1.0.2 to see the correct error and enable Ivy to be able to use DevTools.

Also check https://github.com/rangle/angular-devtools/issues/820 and https://github.com/rangle/angular-devtools/issues/798.
