### ISSUE TITLE
Support Electron

### ISSUE THREAD

**Issue by TobiasTao** [rangle/angular-devtools#849]
**Angular DevTools version (required)**:
1.0.2

**Angular version (required):**
12.0.2

**Link to a minimal stackblitz reproduction (strongly encouraged):**

_Description of issue:_

- Include (clipped) screenshot images if possible.

![image](https://user-images.githubusercontent.com/37654563/120881147-be9a9200-c601-11eb-9e03-f0798b1630f3.png)

_Steps to reproduce:_

```shell
git clone https://github.com/TobiasTao/angular-electron
cd angular-electron
npm install
npm run start
```

error msg:
```
[10168:0606/004415.854:ERROR:CONSOLE(0)] "Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.", source: chrome-extension://lkopochcppfakkbkbhpfnlddnijpffef/index.html (0)
```
_Additional details:_

**Comment by BenjaminDobler** [comment]
I tracked it down to chrome.browserAction calls in background.ts. I guess these are unsupported in electron.
If i comment those calls the extension works nicely in electron. Also add a try catch around these calls fixes the issue.

**Comment by bampakoa** [comment]
I have tested it with the latest version of the extension 1.0.4 and it works as expected 😃

**Comment by TobiasTao** [comment]
🎉
