### ISSUE TITLE
Unable to debug content projected children

### ISSUE THREAD

**Issue by KiranShakya** [rangle/angular-devtools#866]
**What feature do you want to see?**
Current build of angular-devtools doesn't show any content being projected inside a component. Only the component itself is shown.
**Why is it important to you?**
Most of the real life components use content projection widely so this tool is useless in this case.
**Describe functionality in details. Apply mocks if applicable:**
We are unable to find content inside components like ngx-smart-modal, ng-select, and similar other open source components.
_Additional details:_
In the following image, we cannot see anything projected inside of the ngx-smart-modal component.
![image](https://user-images.githubusercontent.com/5449617/123048858-9642ce00-d41e-11eb-93a9-3dc5fd03fdba.png)

**Comment by mgechev** [comment]
What Angular version are you using?

**Comment by KiranShakya** [comment]
@mgechev We are using v11.0.5 of the angular. Thank you.

**Comment by mgechev** [comment]
@KiranShakya this is a known issue in v11. Please update to v12 to get the latest and greatest Angular DevTools experience.
