### ISSUE TITLE
RxJS Observable current value

### ISSUE THREAD

**Issue by dominikfryc** [rangle/angular-devtools#892]
**What feature do you want to see?**
In the properties panel, it would be handy if I could see the current value of RxJS Observable changing in real-time.

**Why is it important to you?**
Now I have to make a console log or print out the value to HTML. This way could save a lot of time instead of writing debug codes.

**Describe functionality in detail. Apply mocks if applicable:**
When I click on the component, there is the properties panel on the right. If the property is Observable, it has 3 properties: *_isScalar*, *operator* and *source*. I would add there a new property *value* with the current value of the Observable.

_Additional details:_
That's just my idea, it could work differently, but I think it would save a lot of time for developers.

**Comment by mgechev** [comment]
We're exploring the alternative of making RxJS optional. Given the direction we're looking into, debugging support for observables is out of the scope for Angular DevTools.

AFAIK, the RxJS team is working on a similar browser extension to provide debugging capabilities for observables. @cartant should be able to share more details.

Closing as out of scope for now.
