### ISSUE TITLE
Safari Support

### ISSUE THREAD

**Issue by david-shortman** [rangle/angular-devtools#895]
**What feature do you want to see?**
Safari extension support

**Why is it important to you?**
Broad spectrum browser support

**Describe functionality in details. Apply mocks if applicable:**
Safari supports modern browser extension APIs, so it should be feasible like the Firefox add-on

_Additional details:_

**Comment by mgechev** [comment]
We wouldn't be able to provide support for Safari because of missing APIs we need. Closing this feature request as out of scope of the project at this point.
