### ISSUE TITLE
Router tree view

### ISSUE THREAD

**Issue by JavaVista** [rangle/angular-devtools#904]
Bring the router tree from Augury

I understand you collaborated with rangle.io to develop this awesome tool and Augury was a great tool. With the Router tree it made very useful to figure out the route of each components when doing Angular and Ionic

Here is an image of the component tree from the Augury extension on ionic angular project
![image](https://user-images.githubusercontent.com/12854968/129069255-e57f5d72-afb3-43e0-88b0-a5386d37090a.png)

**Comment by mgechev** [comment]
This feature is in the roadmap, but we'd first need to develop stable debugging router APIs. I'll close the request for now since it has other dependencies and we don't have a timeline for it just yet.
