### ISSUE TITLE
Several components are not displayed in the Angular Devtools

### ISSUE THREAD

**Issue by jasmine-song** [rangle/angular-devtools#974]
**Angular DevTools version (required)**:
Angular DevTools 1.0.4
**Angular version (required):**
9.1.13 
**Link to a minimal stackblitz reproduction (strongly encouraged):**

_Description of issue:_
   According  the screenshot, I have the component called 'onenote-notebook-paragraph-result', it can show in the host element, but can't find componts in  Angular Devtools

![image](https://user-images.githubusercontent.com/44150070/144821447-09890b25-8e66-4b63-8aac-22148d8605ae.png)

![image](https://user-images.githubusercontent.com/44150070/144817328-79442385-748f-45dc-9fef-40c5043c6dcc.png)

![image](https://user-images.githubusercontent.com/44150070/144823313-21aed428-17b1-4de9-afcf-277249795dcd.png)

_Additional details:_
the 'NotebookparagraphresultComponent' are two components that are looping out, i don't know why only this components don't show

**Comment by mgechev** [comment]
The issue is related to https://github.com/rangle/angular-devtools/issues/773. Make sure you update to Angular v12+ to get proper component view.
